#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Kategorie: Testing
# Kommentar: Runs all GUI (Selenium) tests and can update reference screenshots.

import os
import sys
import argparse
import unittest

def main():
    parser = argparse.ArgumentParser(description="Run GUI/Selenium Test Suite")
    parser.add_argument("--update-pictures", action="store_true", help="Update reference screenshots generated by tests")
    args = parser.parse_args()

    test_dir = os.path.dirname(os.path.abspath(__file__))
    
    if args.update_pictures:
        ref_dir = os.path.join(test_dir, "reference_screenshots")
        os.makedirs(ref_dir, exist_ok=True)
        os.environ["MWV_GUI_PICTURES_DIR"] = ref_dir
        print(f"[*] Screenshot auto-update enabled. Saving to: {ref_dir}")
    else:
        print("[*] Running GUI tests normally. (Use --update-pictures to save new reference screenshots)")

    # Define GUI tests specifically
    gui_tests = [
        "test_playlist_ui",
        "test_ui_events",
        "test_ui_media_visibility",
        "test_gui_tabs_refresh",
        "test_ui_integrity",
        "test_ui_session_stability",
        "test_parser_tab_gui"
    ]

    suite = unittest.TestSuite()
    for test_module in gui_tests:
        try:
            tests = unittest.defaultTestLoader.loadTestsFromName(test_module)
            suite.addTests(tests)
        except Exception as e:
            print(f"Warning: Failed to load {test_module}: {e}")

    # Also add the new picture generator explicitly if we want to run it
    if args.update_pictures:
        # It's a script, not unittest for generate_reference_screenshots.py
        import subprocess
        print("[*] Running generate_reference_screenshots.py to update generic tab pictures...")
        try:
            subprocess.run([sys.executable, "generate_reference_screenshots.py"], cwd=test_dir, check=True)
        except Exception as e:
            print(f"Failed to generate reference screenshots: {e}")

    print("\n[*] Starting GUI Test Suite...")
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    if not result.wasSuccessful():
        sys.exit(1)

if __name__ == "__main__":
    # Ensure sys.path contains the tests directory
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    main()
